### ISSUE TITLE
complete search function 

### ISSUE THREAD

**Issue by kmrakash** [kmrakash/HELLO_WORLD#9]
Feature : user can Search the language Card

**Comment by reverk** [comment]
Hi! Can I work on this issue?

**Comment by kmrakash** [comment]
Yeah sure @reverk , go ahead think of a approach n let me know

**Comment by reverk** [comment]
@kmrakash Thanks for assigning me. I found [List.js](https://listjs.com/). It seems to fit well in this case.

In a nutshell, Listjs filters out and shows the result as a user is typing. 

I also found that it might be possible to shorten HTML code and let JavaScript to loop all the data (language name, contributor etc.). See [List.js Docs](https://listjs.com/docs/), Example 2 & 6. I've yet to fiddle with this -- so that will be another issue to look at.

What do you think?

**Comment by kmrakash** [comment]
That's a great idea @reverk  , go ahead
